var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");(new WOW).init();
jQuery(window).resize(function(){jQuery(".navbar-collapse").css({maxHeight:$(window).height()-$(".navbar-header").height()+"px"})});
$(window).load(function(){function a(a){a.is(":visible")||a.slideDown("fast")}function b(){d=matchMedia("(min-width:667px)").matches;e=0<$(".sticky-wrapper").length;if(d&&!e)c.sticky({topSpacing:0}).on({"sticky-start":function(){a($mainNav)},"sticky-end":function(){a($mainNav)}});else c.unstick()}var c=$(".sticky"),d=!0,e=!0;$mainNav=$(".main-nav");b();$(window).resize($.debounce(1E3,b))});
$.fn.productItemReview=function(){var a=this,b,c,d,e=/\d+/g;$([function(){b=a.find(">div.feedbackBG").addClass("rating").next().find("b").text();c=parseInt(b.match(e));d="<h3>Reviews";isNaN(c)||(d+=' (<span class="count">'+c+"</span>)");d+="</h3>";a.addClass("reviews-widget").prepend(d)},function(){a.find(">p").addClass("global-rating");a.find("table,tbody").css({display:"block",width:"auto"}).find(".head td:eq(0),.head td:eq(1)").css("display","block");a.find("tr").css("display","block").not(".head").find("td").css("display",
"block");a.find("table").addClass("review-body").css({"font-size":"0.875em","line-height":"1.25em"}).find(".head>td:first-child").css({"float":"left",width:"auto"});a.find("table").find(".head").css("margin-bottom","0").each(function(){$(this).addClass("review").find(".title").addClass("review-title").find("strong").replaceWith('<h5 style="margin-top:2px;">'+$(this).find(".title strong").text()+"</h5>")})},function(){a.find(".head").find("td:eq(1)",a).css("display","block");a.find(".head").find("td:gt(2)",
this).prepend('<span style="display:inline-block; margin:0 8px;">|&nbsp;</span>')},function(){a.find("tr",a).filter(":not(.head)",a).find("td:eq(0)",a).hide()}]).each(function(a,b){b()})};$("#reviewLink>span").productItemReview();
jQuery(document).ready(function(){$("header .main-nav").clickMenu();$(".toggle-menu-header").on("click",function(a){a.preventDefault();$("body").toggleClass("sticky-menu");$(".is-sticky .main-nav").slideToggle()});matchMedia("(max-width:767px)").matches&&$(".top-categories .blocks-main").slick({prevArrow:"<button type='button' data-role='none' class='slick-prev'><span class='visuallyhidden'>Previous</span><span class='icon-arrowleft'></span></button>",nextArrow:"<button type='button' data-role='none' class='slick-next'><span class='visuallyhidden'>Next</span><span class='icon-arrowright'></span></button>"});
$(".hero-banner").slick({dots:!0,autoplay:!0,autoplaySpeed:8E3,prevArrow:"<button type='button' data-role='none' class='slick-prev'><span class='visuallyhidden'>Previous</span><span class='icon-arrowleft'></span></button>",nextArrow:"<button type='button' data-role='none' class='slick-next'><span class='visuallyhidden'>Next</span><span class='icon-arrowright'></span></button>"});$(".top-products").slick({infinite:!0,slidesToShow:5,slidesToScroll:1,prevArrow:"<button type='button' data-role='none' class='slick-prev'><span class='visuallyhidden'>Previous</span><span class='icon-arrowleft'></span></button>",
nextArrow:"<button type='button' data-role='none' class='slick-next'><span class='visuallyhidden'>Next</span><span class='icon-arrowright'></span></button>",responsive:[{breakpoint:767,settings:{slidesToShow:1,slidesToScroll:1,infinite:!0}},{breakpoint:1199,settings:{slidesToShow:3,slidesToScroll:1,infinite:!0}}]});$(".single-product-slider").slick({infinite:!0,slidesToShow:1,slidesToScroll:1,prevArrow:"<button type='button' data-role='none' class='slick-prev'><span class='visuallyhidden'>Previous</span><span class='icon-arrowleft'></span></button>",
nextArrow:"<button type='button' data-role='none' class='slick-next'><span class='visuallyhidden'>Next</span><span class='icon-arrowright'></span></button>",asNavFor:".alt-views",dots:!0});$(".alt-views").slick({slidesToShow:7,slidesToScroll:1,asNavFor:".single-product-slider",dots:!1,focusOnSelect:!0,infinite:!1,prevArrow:"<button type='button' data-role='none' class='slick-prev'><span class='visuallyhidden'>Previous</span><span class='icon-arrowleft'></span></button>",nextArrow:"<button type='button' data-role='none' class='slick-next'><span class='visuallyhidden'>Next</span><span class='icon-arrowright'></span></button>"})});
jQuery(document).ready(function(){1199>=screen.width&&$(".callouts").clone().appendTo("main");$("footer ul.link-list").on("click",".expand-trigger",function(a){a.preventDefault();$(this).children(".fa").toggleClass("fa-caret-up").closest("li").find("ul.list-unstyled").toggle()});$(".footer .contact .showroom-text").on("click",function(a){a.preventDefault();$(this).children(".expand-trigger").children("span").toggleClass("icon-plus").toggleClass("icon-minus").closest("li").find("p").toggle()});$(".ordering-insturctions textarea").attr("placeholder",
"Enter ordering instructions here");$(".ordering-insturctions textarea").addClass("form-control");$(".gc-form input").addClass("form-control gc-number");$(".form-control.gc-number").attr("placeholder","Number");$(".gc-form input+input").addClass("form-control gc-pin");$(".form-control.gc-pin").attr("placeholder","Pin");$(".form-control.gc-pin").removeClass("gc-number");$(".gc-form input+input+input").addClass("btn btn-secondary");$(".gc-form input+input+input").removeClass("form-control gc-pin");
$(".gc-form input+input+input").removeClass("button375");$('.gc-form:contains("Number:")').each(function(){$(this).html($(this).html().split("Number:").join(""))});$('.gc-form:contains("PIN:")').each(function(){$(this).html($(this).html().split("PIN:").join(""))});$('.gc-form:contains(":")').each(function(){$(this).html($(this).html().split(":").join(""))});$(".coupon-code input").addClass("form-control");$(".coupon-code input+input").removeClass("form-control button152");$(".coupon-code input+input").addClass("btn btn-secondary");
$(".google_button span").removeAttr("style");$(".google_button #CBP_wrapper").removeAttr("style");$(".google_button span").addClass("button_disp_inline_block");$(".google_button span+span+span").removeClass("button_disp_inline_block");$(".google_button span+span+span").addClass("button_disp_block");$(".google_button span+span+span input").removeClass("button8");$(".google_button span+span+span input").addClass("btn-block-check");$('.table-condensed #ss_payment:contains("Select payment type:")').each(function(){$(this).html($(this).html().split("Select payment type:").join(""))});
$(".zipncountry tr").addClass("select-option");$(".zipncountry td.zipncountry_txt").attr("style","display:none;");$(".zipncountry td.zipncountry input").addClass("form-control");$(".zipncountry td.zipncountry input").attr("placeholder","Enter Zip");$(".zipncountry tr+tr+tr").addClass("second")});jQuery(window).load(function(){jQuery(".content-scroll").mCustomScrollbar({advanced:{updateOnContentResize:!0},scrollButtons:{enable:!1},mouseWheelPixels:"200",theme:"dark-2"})});jQuery(function(){jQuery('[data-toggle="tooltip"]').tooltip()});
jQuery(document).ready(function(){$(".item_holder .title h5").matchHeight();$(".category-list-thumb h3").matchHeight();$(".category-brand-list-thumb").matchHeight();$(".product-listing .product-listing-row .item_holder .title h2").matchHeight();$("ul.sub-menu-list li").matchHeight();$(".brand-list-thumb h3").matchHeight()});
jQuery(document).ready(function(){$(".hawk-railNavHeading").on("click",function(){var a=$(this),b=a.next(".hawkRailNav");a.toggleClass("hawk-railNavHeadingActive");b.toggleClass("hawk-notCollapsed")});$(".hawk-guidedNavWrapper .hawk-navGroup .hawk-groupHeading").on("click",function(){$(this).closest(".hawk-navGroup").toggleClass("hawk-notCollapsed")});$(".hawk-guidedNavWrapper .hawk-collapsible .hawk-groupHeading").on("click",function(){var a=$(this).closest(".hawk-navGroup");a.toggleClass("hawk-collapsed");
a.attr("data-field");a.hasClass("hawk-collapsed")});$(".hawkRailNav").delegate(".hawk-navGroup li a","mouseover mouseout click",function(a){var b=$(this).parent();"mouseover"==a.type?b.addClass("hawkFacet-hover"):"mouseout"==a.type?b.removeClass("hawkFacet-hover"):"click"==a.type&&(a.preventDefault(),b.toggleClass("hawkFacet-active"))})});
