/*
 CLICK NAVIGATION FUNCTIONALITY
/* Version: 1.0
/* Author: Nick Goodrum
/* Followed WAI-ARIA spec except for typing a letter key keyboard functionality
/* TO DO - CALLBACKS, DATA-ATTRIBUTES, CLEARING FOCUS CLASS WHEN TABBED AWAY WITHOUT OPENING MENU */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(b,f,e){b instanceof String&&(b=String(b));for(var c=b.length,a=0;a<c;a++){var g=b[a];if(f.call(e,g,a,b))return{i:a,v:g}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,f,e){b!=Array.prototype&&b!=Object.prototype&&(b[f]=e.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(b,f,e,c){if(f){e=$jscomp.global;b=b.split(".");for(c=0;c<b.length-1;c++){var a=b[c];a in e||(e[a]={});e=e[a]}b=b[b.length-1];c=e[b];f=f(c);f!=c&&null!=f&&$jscomp.defineProperty(e,b,{configurable:!0,writable:!0,value:f})}};$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(b,e){return $jscomp.findInternal(this,b,e).v}},"es6","es3");
(function(b){function f(){return matchMedia("(min-width:768px)").matches}var e=function(a,b,k){var d;return function(){var g=this,c=arguments,h=k&&!d;clearTimeout(d);d=setTimeout(function(){d=null;k||a.apply(g,c)},b);h&&a.apply(g,c)}};Function.prototype.bind||(Function.prototype.bind=function(){var a=this,b=Array.prototype.slice.call(arguments),c=b.shift();return function(){return a.apply(c,b.concat(Array.prototype.slice.call(arguments)))}});var c=function(){return function(a,g){this.defaults={menutype:"dropdown",
animationSpeed:400,toggle:"toggle-menu",menu:"cm-menu",htmlClass:"cm-js-menu-active",expanderText:"expand / collapse",landings:!1,expanders:!1,singleClick:!0,fadeObject:"#cmlla"};var c=b(a).data()||{};this.options=b.extend({},this.defaults,c,g);this.menu=a;this.$menu=b(a);this.$menuBar=this.$menu.find("."+this.options.menu);this.$menuToggle=this.$menu.find("."+this.options.toggle);this.isActive=!1;this.lastEventType;this.currentFocus=0;this.initialLinks=[];this.currentLinks=[];this.keyHandler=b.proxy(this.keyHandler,
this);this.showMenu=b.proxy(this.showMenu,this);this.hideMenu=b.proxy(this.hideMenu,this);this.menuToggle=b.proxy(this.menuToggle,this);this.fadeToggle=b.proxy(this.fadeToggle,this);this.subMenuToggle=b.proxy(this.subMenuToggle,this);this.menuHandler=b.proxy(this.menuHandler,this);this.menuToggleHandler=b.proxy(this.menuToggleHandler,this);this.init()}}();c.prototype.init=function(){var a=this;a.$menuToggle.on("click touchstart",a.menuToggle);a.$menu.addClass("cm-js-enabled").attr({role:"navigation",
tabindex:"0"});a.$menuBar.attr("role","menubar");var g=1;if(0<b("[id^='cm-dropdown']").last().length){var c=0;b("[id^='cm-dropdown']").each(function(){var a=b(this).attr("id").split("dropdown")[1];c=a&&c<parseInt(a,10)?parseInt(a,10):c});g=c+1}a.$menu.on("keydown",a.keyHandler);a.$menu.on("focus",function(){a.$menuToggle.is(":visible")&&!a.isActive&&a.showMenu();a.$menu.hasClass("cm-js-inFocus")||a.isActive||(a.$menu.addClass("cm-js-inFocus").attr("tabindex","-1"),a.currentLinks[a.currentFocus].attr("tabindex",
"0").focus())});a.initialLinks=[];a.$menu.find("."+a.options.menu+" a").each(function(){var d=b(this),c=d.closest("li");d.attr({role:"menuitem",tabindex:"-1"});c.attr("role","presentation");!c.data("type")&&c.parent().hasClass(a.options.menu)&&c.attr("data-type",a.options.menutype);if(0<d.siblings().not("a").length){var k=d.siblings(),h="cm-dropdown"+g;if(a.options.expanders){var f=b("<a id='"+h+"' href='#' role='menuitem' aria-haspopup='true' class='has-sub' tabindex='-1'><span><span class='visually-hidden'>"+
a.options.expanderText+"</span></span></a>");d.wrap("<div class='expander-wrap'></div>").after(f);f.on("click",a.subMenuToggle)}else d.attr("id")?h=d.attr("id"):d.attr("id","cm-dropdown"+g),d.attr({"aria-haspopup":"true"}).addClass("has-sub").on("click",a.subMenuToggle);var l=0<k.height()?!0:!1;k.attr({role:"menu","aria-expanded":l,"aria-hidden":!l,"aria-labelledby":h});a.options.landings&&!a.options.expanders&&(l=k.is("ul")?b("<li class='link-landing'>"+d.get(0).outerHTML+"</li>"):b("<div class='link-landing'>"+
d.get(0).outerHTML+"</div>"),l.children().removeAttr("aria-haspopup class id"),l.find("a").removeClass("has-sub"),k.prepend(l));if(c.data("type")&&"sliding"===c.data("type")){l=b("<div class='sub-menu cm-js-inactive'></div>");k.wrap(l);var p=function(){var b=a.$menu.innerWidth(),d=c.position().left;var g=c.children(".sub-menu");g.find("> ul > li > ul").innerWidth(b);g.innerWidth(b).css("left","-"+d+"px")},r=e(p,300);b(window).load(function(){p();b(window).resize(r)})}h==="cm-dropdown"+g&&g++}d.closest("[role]:not(a)").data("type")&&
(a.initialLinks.push(d),a.options.expanders&&a.initialLinks.push(f))});a.currentLinks=a.initialLinks};c.prototype.keyHandler=function(a){this.$menu.hasClass("cm-js-inFocus")||this.$menu.addClass("cm-js-inFocus").attr("tabindex","-1");if(37===a.keyCode||38===a.keyCode||39===a.keyCode||40===a.keyCode){a.preventDefault();var b=this.currentLinks[this.currentFocus];if(b){var c=b.closest("[role]:not(a)").attr("data-type"),d=b.closest("[role=menu]:not(a)").closest("[role=presentation]").attr("data-type"),
f;if(c)if(37===a.keyCode)var e="prev";else if(39===a.keyCode)e="next";else{if(40===a.keyCode||38===a.keyCode)var h=!0}else 38===a.keyCode?e="prev":40===a.keyCode?e="next":39===a.keyCode?h=!0:d||37!==a.keyCode||(f=!0);if(e){this.currentFocus="prev"===e?0<=this.currentFocus-1?this.currentFocus-1:this.currentLinks.length-1:this.currentFocus+1<this.currentLinks.length?this.currentFocus+1:0;var q=this.currentLinks[this.currentFocus]}q?(b.attr("tabindex","-1"),this.currentLinks[this.currentFocus].attr("tabindex",
"0").focus()):f?this.$menu.find(".opened").last().find("[aria-haspopup]").first().trigger("click"):h&&(b.closest("li").hasClass("clicked")||this.currentLinks[this.currentFocus].trigger("click"))}}else 27===a.keyCode?(a.preventDefault(),this.$menu.find(".opened").last().find("[aria-haspopup]").first().trigger("click")):32===a.keyCode&&(a.preventDefault(),this.currentLinks[this.currentFocus].trigger("click"))};c.prototype.cleanUpEvents=function(){this.$menu.find("li a").off("click",this.subMenuToggle);
this.$menu.find("li a[tabindex=0]").attr("tabindex","-1");this.$menu.off("focus");this.$menu.off("keydown",this.keyHandler);b("html").off("click touchstart focusin",this.menuHandler);b("html").off("click touchstart",this.menuToggleHandler)};c.prototype.destroy=function(){this.$menu.removeClass("cm-js-enabled cm-js-inFocus");this.$menu.find("li").removeClass("opened animating animated");this.cleanUpEvents()};c.prototype.showMenu=function(){var a=this;a.isActive=!0;a.$menu.addClass("cm-js-active");
a.$menuToggle.addClass("active");b("html").addClass(a.options.htmlClass);a.$menu.focus();b("html").off("click touchstart",a.menuToggleHandler);f()&&setTimeout(function(){b("html").addClass(a.options.htmlClass).on("click touchstart focusin",a.menuToggleHandler)},a.options.animationSpeed);a.fadeToggle(!0)};c.prototype.hideMenu=function(){this.isActive=!1;this.$menu.removeClass("cm-js-active cm-js-inFocus");this.$menuToggle.removeClass("active");f()&&b("html").removeClass(this.options.htmlClass).addClass("cm-animate-out").off("click touchstart focusin",
this.menuToggleHandler);setTimeout(function(){b("html").removeClass("cm-animate-out")},this.options.animationSpeed);this.fadeToggle(!0)};c.prototype.menuToggle=function(a){a.preventDefault();if("touchstart"!==this.lastEventType||"click"!==a.type)this.isActive?this.hideMenu():this.showMenu();this.lastEventType=a.type};c.prototype.fadeToggle=function(a,c){var g=b(this.$menu),d=b(this.options.fadeObject);a?d.toggleClass("activeMobi"):g.find(".toggle-menu").is(":visible")||(c&&d.hasClass("active")&&!g.find(".cm-menu>li").hasClass("opened")?
(d.removeClass("active"),setTimeout(function(){d.removeClass("opened")},this.options.animationSpeed)):!d.hasClass("active")&&g.find(".cm-menu>li").hasClass("opened")&&d.addClass("opened active"))};c.prototype.subMenuToggle=function(a){var c=this,e=b(a.currentTarget),d=e.closest("li"),m=e.closest("[data-type]").data("type"),n=b("[aria-labelledby="+e.attr("id")+"]");if(d.hasClass("opened")){b("html").off("click touchstart focusin",c.menuHandler);if(c.options.singleClick){a.preventDefault();"sliding"===
m&&d.parents(".sub-menu").hasClass("sub-menu")&&d.parents(".sub-menu").addClass("cm-js-inactive");d.removeClass("opened animating animated");if(0<c.$menu.find(".opened").length)b("html").on("click touchstart focusin",c.menuHandler);n.attr({"aria-expanded":"false","aria-hidden":"true"});b.each(c.currentLinks,function(){this.attr("tabindex","-1")});c.currentLinks=[];setTimeout(function(){if(d.data("type"))c.currentLinks=c.initialLinks,c.currentFocus=d.index();else{var a=0;d.closest("[role=menu]").find("a").each(function(d,
g){d=b(g);10<d.closest("[role=menu]").height()&&10<d.closest("[role=menu]").width()&&(c.currentLinks.push(d),e.attr("id")===d.attr("id")&&(c.currentFocus=a),a++)})}e.attr("tabindex","0").focus()},c.options.animationSpeed)}c.fadeToggle(!1,!0)}else a.preventDefault(),d.addClass("opened animating").siblings().removeClass("opened animating animated").find(".opened").removeClass("opened animating animated"),d.siblings().find(".sub-menu").addClass("cm-js-inactive"),"sliding"===m&&0<d.parents(".sub-menu").length&&
d.parents(".sub-menu").removeClass("cm-js-inactive"),n.attr({"aria-expanded":"true","aria-hidden":"false"}),b.each(c.currentLinks,function(){this.attr("tabindex","-1")}),c.currentLinks=[],setTimeout(function(){d.hasClass("animating")&&d.removeClass("animating").addClass("animated");d.find("[role=menu]").first().find("a").each(function(a,d){a=b(d);10<a.closest("[role=menu]").height()&&10<a.closest("[role=menu]").width()&&c.currentLinks.push(a)});"false"==d.find(".sub-menu-list").first().attr("aria-expanded")&&
c.currentLinks[0].trigger("click");"sub-menu cm-js-inactive"==d.find(".sub-menu").attr("class")&&c.currentLinks[0].trigger("click");c.currentFocus=0;c.currentLinks[c.currentFocus].attr("tabindex","0").focus();if(f())b("html").on("click touchstart focusin",c.menuHandler)},c.options.animationSpeed),c.fadeToggle(!1,!1)};c.prototype.menuToggleHandler=function(a){b.contains(this.menu,a.target)||(this.$menu.find("."+this.options.toggle).trigger("click"),b("html").removeClass(this.options.htmlClass).off("click touchstart",
this.menuToggleHandler))};c.prototype.menuHandler=function(a){b.contains(this.menu,a.target)||this.$menu.is(b(a.target))||(this.$menu.find(".opened").removeClass("opened animated animating"),this.$menu.find("[role=menu]").attr({"aria-expanded":"false","aria-hidden":"false"}),this.$menu.find(".sub-menu").addClass("cm-js-inactive"),this.$menu.find("li a[tabindex=0]").attr("tabindex","-1"),this.currentLinks=this.initialLinks,this.currentFocus=0,b(".cm-js-inFocus").removeClass("cm-js-inFocus").attr("tabindex",
"0"),b("html").off("click touchstart focusin",this.menuHandler),this.fadeToggle(!1,!0))};b.fn.clickMenu=function(){var a=arguments[0],b=Array.prototype.slice.call(arguments,1),e=this.length,d=0,f;for(d;d<e;d++)if("object"==typeof a||"undefined"==typeof a?this[d].clickMenu=new c(this[d],a):f=this[d].clickMenu[a].apply(this[d].clickMenu,b),"undefined"!=typeof f)return f;return this}})(jQuery);
