/*
 The MIT License (MIT)
 @todo Lazy Load Icon
 @todo prevent animationend bubling
 @todo itemsScaleUp
 @todo Test Zepto
 @todo stagePadding calculate wrong active classes
 The MIT License (MIT)
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,e,k){a instanceof String&&(a=String(a));for(var h=a.length,c=0;c<h;c++){var f=a[c];if(e.call(k,f,c,a))return{i:c,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,e,k){a!=Array.prototype&&a!=Object.prototype&&(a[e]=k.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,e,k,h){if(e){k=$jscomp.global;a=a.split(".");for(h=0;h<a.length-1;h++){var c=a[h];c in k||(k[c]={});k=k[c]}a=a[a.length-1];h=k[a];e=e(h);e!=h&&null!=e&&$jscomp.defineProperty(k,a,{configurable:!0,writable:!0,value:e})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,k){return $jscomp.findInternal(this,a,k).v}},"es6","es3");
(function(a,e,k,h){function c(b,d){this.settings=null;this.options=a.extend({},c.Defaults,d);this.$element=a(b);this.drag=a.extend({},g);this.state=a.extend({},l);this.e=a.extend({},m);this._plugins={};this._supress={};this._speed=this._current=null;this._coordinates=[];this._width=this._breakpoint=null;this._items=[];this._clones=[];this._mergers=[];this._invalidated={};this._pipe=[];a.each(c.Plugins,a.proxy(function(b,a){this._plugins[b[0].toLowerCase()+b.slice(1)]=new a(this)},this));a.each(c.Pipe,
a.proxy(function(b,d){this._pipe.push({filter:d.filter,run:a.proxy(d.run,this)})},this));this.setup();this.initialize()}function f(b){if(b.touches!==h)return{x:b.touches[0].pageX,y:b.touches[0].pageY};if(b.touches===h){if(b.pageX!==h)return{x:b.pageX,y:b.pageY};if(b.pageX===h)return{x:b.clientX,y:b.clientY}}}function d(b){var a,d=k.createElement("div");for(a in b){var c=b[a];if("undefined"!==typeof d.style[c])return[c,a]}return[!1]}var g={start:0,startX:0,startY:0,current:0,currentX:0,currentY:0,
offsetX:0,offsetY:0,distance:null,startTime:0,endTime:0,updatedX:0,targetEl:null};var l={isTouch:!1,isScrolling:!1,isSwiping:!1,direction:!1,inMotion:!1};var m={_onDragStart:null,_onDragMove:null,_onDragEnd:null,_transitionEnd:null,_resizer:null,_responsiveCall:null,_goToLoop:null,_checkVisibile:null};c.Defaults={items:3,loop:!1,center:!1,mouseDrag:!0,touchDrag:!0,pullDrag:!0,freeDrag:!1,margin:0,stagePadding:0,merge:!1,mergeFit:!0,autoWidth:!1,startPosition:0,rtl:!1,smartSpeed:250,fluidSpeed:!1,
dragEndSpeed:!1,responsive:{},responsiveRefreshRate:200,responsiveBaseElement:e,responsiveClass:!1,fallbackEasing:"swing",info:!1,nestedItemSelector:!1,itemElement:"div",stageElement:"div",themeClass:"owl-theme",baseClass:"owl-carousel",itemClass:"owl-item",centerClass:"center",activeClass:"active"};c.Width={Default:"default",Inner:"inner",Outer:"outer"};c.Plugins={};c.Pipe=[{filter:["width","items","settings"],run:function(b){b.current=this._items&&this._items[this.relative(this._current)]}},{filter:["items",
"settings"],run:function(){var b=this._clones;if(this.$stage.children(".cloned").length!==b.length||!this.settings.loop&&0<b.length)this.$stage.children(".cloned").remove(),this._clones=[]}},{filter:["items","settings"],run:function(){var b,a=this._clones,d=this._items,c=this.settings.loop?a.length-Math.max(2*this.settings.items,4):0;var f=0;for(b=Math.abs(c/2);f<b;f++)0<c?(this.$stage.children().eq(d.length+a.length-1).remove(),a.pop(),this.$stage.children().eq(0).remove(),a.pop()):(a.push(a.length/
2),this.$stage.append(d[a[a.length-1]].clone().addClass("cloned")),a.push(d.length-1-(a.length-1)/2),this.$stage.prepend(d[a[a.length-1]].clone().addClass("cloned")))}},{filter:["width","items","settings"],run:function(){var b=this.settings.rtl?1:-1,a=(this.width()/this.settings.items).toFixed(3),d=0,c;this._coordinates=[];var f=0;for(c=this._clones.length+this._items.length;f<c;f++){var g=this._mergers[this.relative(f)];g=this.settings.mergeFit&&Math.min(g,this.settings.items)||g;d+=(this.settings.autoWidth?
this._items[this.relative(f)].width()+this.settings.margin:a*g)*b;this._coordinates.push(d)}}},{filter:["width","items","settings"],run:function(){var b;var d=(this.width()/this.settings.items).toFixed(3);var c={width:Math.abs(this._coordinates[this._coordinates.length-1])+2*this.settings.stagePadding,"padding-left":this.settings.stagePadding||"","padding-right":this.settings.stagePadding||""};this.$stage.css(c);c={width:this.settings.autoWidth?"auto":d-this.settings.margin};c[this.settings.rtl?"margin-left":
"margin-right"]=this.settings.margin;if(!this.settings.autoWidth&&0<a.grep(this._mergers,function(b){return 1<b}).length)for(d=0,b=this._coordinates.length;d<b;d++)c.width=Math.abs(this._coordinates[d])-Math.abs(this._coordinates[d-1]||0)-this.settings.margin,this.$stage.children().eq(d).css(c);else this.$stage.children().css(c)}},{filter:["width","items","settings"],run:function(b){b.current&&this.reset(this.$stage.children().index(b.current))}},{filter:["position"],run:function(){this.animate(this.coordinates(this._current))}},
{filter:["width","position","items","settings"],run:function(){var b=this.settings.rtl?1:-1,a=2*this.settings.stagePadding,d=this.coordinates(this.current())+a,c=d+this.width()*b,f=[],g;var e=0;for(g=this._coordinates.length;e<g;e++){var l=this._coordinates[e-1]||0;var m=Math.abs(this._coordinates[e])+a*b;(this.op(l,"<=",d)&&this.op(l,">",c)||this.op(m,"<",d)&&this.op(m,">",c))&&f.push(e)}this.$stage.children("."+this.settings.activeClass).removeClass(this.settings.activeClass);this.$stage.children(":eq("+
f.join("), :eq(")+")").addClass(this.settings.activeClass);this.settings.center&&(this.$stage.children("."+this.settings.centerClass).removeClass(this.settings.centerClass),this.$stage.children().eq(this.current()).addClass(this.settings.centerClass))}}];c.prototype.initialize=function(){this.trigger("initialize");this.$element.addClass(this.settings.baseClass).addClass(this.settings.themeClass).toggleClass("owl-rtl",this.settings.rtl);this.browserSupport();if(this.settings.autoWidth&&!0!==this.state.imagesLoaded){var b=
this.$element.find("img");var d=this.$element.children(this.settings.nestedItemSelector?"."+this.settings.nestedItemSelector:h).width();if(b.length&&0>=d)return this.preloadAutoWidthImages(b),!1}this.$element.addClass("owl-loading");this.$stage=a("<"+this.settings.stageElement+' class="owl-stage"/>').wrap('<div class="owl-stage-outer">');this.$element.append(this.$stage.parent());this.replace(this.$element.children().not(this.$stage.parent()));this._width=this.$element.width();this.refresh();this.$element.removeClass("owl-loading").addClass("owl-loaded");
this.eventsCall();this.internalEvents();this.addTriggerableEvents();this.trigger("initialized")};c.prototype.setup=function(){var b=this.viewport(),d=this.options.responsive,c=-1,f=null;d?(a.each(d,function(a){a<=b&&a>c&&(c=Number(a))}),f=a.extend({},this.options,d[c]),delete f.responsive,f.responsiveClass&&this.$element.attr("class",function(b,a){return a.replace(/\b owl-responsive-\S+/g,"")}).addClass("owl-responsive-"+c)):f=a.extend({},this.options);if(null===this.settings||this._breakpoint!==
c)this.trigger("change",{property:{name:"settings",value:f}}),this._breakpoint=c,this.settings=f,this.invalidate("settings"),this.trigger("changed",{property:{name:"settings",value:this.settings}})};c.prototype.optionsLogic=function(){this.$element.toggleClass("owl-center",this.settings.center);this.settings.loop&&this._items.length<this.settings.items&&(this.settings.loop=!1);this.settings.autoWidth&&(this.settings.stagePadding=!1,this.settings.merge=!1)};c.prototype.prepare=function(b){var d=this.trigger("prepare",
{content:b});d.data||(d.data=a("<"+this.settings.itemElement+"/>").addClass(this.settings.itemClass).append(b));this.trigger("prepared",{content:d.data});return d.data};c.prototype.update=function(){for(var b=0,d=this._pipe.length,c=a.proxy(function(b){return this[b]},this._invalidated),f={};b<d;)(this._invalidated.all||0<a.grep(this._pipe[b].filter,c).length)&&this._pipe[b].run(f),b++;this._invalidated={}};c.prototype.width=function(b){b=b||c.Width.Default;switch(b){case c.Width.Inner:case c.Width.Outer:return this._width;
default:return this._width-2*this.settings.stagePadding+this.settings.margin}};c.prototype.refresh=function(){if(0===this._items.length)return!1;(new Date).getTime();this.trigger("refresh");this.setup();this.optionsLogic();this.$stage.addClass("owl-refresh");this.update();this.$stage.removeClass("owl-refresh");this.state.orientation=e.orientation;this.watchVisibility();this.trigger("refreshed")};c.prototype.eventsCall=function(){this.e._onDragStart=a.proxy(function(b){this.onDragStart(b)},this);this.e._onDragMove=
a.proxy(function(b){this.onDragMove(b)},this);this.e._onDragEnd=a.proxy(function(b){this.onDragEnd(b)},this);this.e._onResize=a.proxy(function(b){this.onResize(b)},this);this.e._transitionEnd=a.proxy(function(b){this.transitionEnd(b)},this);this.e._preventClick=a.proxy(function(b){this.preventClick(b)},this)};c.prototype.onThrottledResize=function(){e.clearTimeout(this.resizeTimer);this.resizeTimer=e.setTimeout(this.e._onResize,this.settings.responsiveRefreshRate)};c.prototype.onResize=function(){if(!this._items.length||
this._width===this.$element.width()||this.trigger("resize").isDefaultPrevented())return!1;this._width=this.$element.width();this.invalidate("width");this.refresh();this.trigger("resized")};c.prototype.eventsRouter=function(b){var a=b.type;if("mousedown"===a||"touchstart"===a)this.onDragStart(b);else if("mousemove"===a||"touchmove"===a)this.onDragMove(b);else if("mouseup"===a||"touchend"===a)this.onDragEnd(b);else if("touchcancel"===a)this.onDragEnd(b)};c.prototype.internalEvents=function(){var b=
e.navigator.msPointerEnabled;this.settings.mouseDrag?(this.$stage.on("mousedown",a.proxy(function(b){this.eventsRouter(b)},this)),this.$stage.on("dragstart",function(){return!1}),this.$stage.get(0).onselectstart=function(){return!1}):this.$element.addClass("owl-text-select-on");if(this.settings.touchDrag&&!b)this.$stage.on("touchstart touchcancel",a.proxy(function(b){this.eventsRouter(b)},this));if(this.transitionEndVendor)this.on(this.$stage.get(0),this.transitionEndVendor,this.e._transitionEnd,
!1);if(!1!==this.settings.responsive)this.on(e,"resize",a.proxy(this.onThrottledResize,this))};c.prototype.onDragStart=function(b){b=b.originalEvent||b||e.event;if(3===b.which||this.state.isTouch)return!1;"mousedown"===b.type&&this.$stage.addClass("owl-grab");this.trigger("drag");this.drag.startTime=(new Date).getTime();this.speed(0);this.state.isTouch=!0;this.state.isScrolling=!1;this.state.isSwiping=!1;this.drag.distance=0;var d=f(b).x;var c=f(b).y;this.drag.offsetX=this.$stage.position().left;
this.drag.offsetY=this.$stage.position().top;this.settings.rtl&&(this.drag.offsetX=this.$stage.position().left+this.$stage.width()-this.width()+this.settings.margin);if(this.state.inMotion&&this.support3d){var g=this.getTransformProperty();this.drag.offsetX=g;this.animate(g);this.state.inMotion=!0}else if(this.state.inMotion&&!this.support3d)return this.state.inMotion=!1;this.drag.startX=d-this.drag.offsetX;this.drag.startY=c-this.drag.offsetY;this.drag.start=d-this.drag.startX;this.drag.targetEl=
b.target||b.srcElement;this.drag.updatedX=this.drag.start;if("IMG"===this.drag.targetEl.tagName||"A"===this.drag.targetEl.tagName)this.drag.targetEl.draggable=!1;a(k).on("mousemove.owl.dragEvents mouseup.owl.dragEvents touchmove.owl.dragEvents touchend.owl.dragEvents",a.proxy(function(b){this.eventsRouter(b)},this))};c.prototype.onDragMove=function(b){if(this.state.isTouch&&!this.state.isScrolling){b=b.originalEvent||b||e.event;var a=f(b).x;var d=f(b).y;this.drag.currentX=a-this.drag.startX;this.drag.currentY=
d-this.drag.startY;this.drag.distance=this.drag.currentX-this.drag.offsetX;0>this.drag.distance?this.state.direction=this.settings.rtl?"right":"left":0<this.drag.distance&&(this.state.direction=this.settings.rtl?"left":"right");if(this.settings.loop)this.op(this.drag.currentX,">",this.coordinates(this.minimum()))&&"right"===this.state.direction?this.drag.currentX-=(this.settings.center&&this.coordinates(0))-this.coordinates(this._items.length):this.op(this.drag.currentX,"<",this.coordinates(this.maximum()))&&
"left"===this.state.direction&&(this.drag.currentX+=(this.settings.center&&this.coordinates(0))-this.coordinates(this._items.length));else{a=this.settings.rtl?this.coordinates(this.maximum()):this.coordinates(this.minimum());d=this.settings.rtl?this.coordinates(this.minimum()):this.coordinates(this.maximum());var c=this.settings.pullDrag?this.drag.distance/5:0;this.drag.currentX=Math.max(Math.min(this.drag.currentX,a+c),d+c)}if(8<this.drag.distance||-8>this.drag.distance)b.preventDefault!==h?b.preventDefault():
b.returnValue=!1,this.state.isSwiping=!0;this.drag.updatedX=this.drag.currentX;(16<this.drag.currentY||-16>this.drag.currentY)&&!1===this.state.isSwiping&&(this.state.isScrolling=!0,this.drag.updatedX=this.drag.start);this.animate(this.drag.updatedX)}};c.prototype.onDragEnd=function(b){if(this.state.isTouch){"mouseup"===b.type&&this.$stage.removeClass("owl-grab");this.trigger("dragged");this.drag.targetEl.removeAttribute("draggable");this.state.isTouch=!1;this.state.isScrolling=!1;this.state.isSwiping=
!1;if(0===this.drag.distance&&!0!==this.state.inMotion)return this.state.inMotion=!1;this.drag.endTime=(new Date).getTime();b=this.drag.endTime-this.drag.startTime;(3<Math.abs(this.drag.distance)||300<b)&&this.removeClick(this.drag.targetEl);b=this.closest(this.drag.updatedX);this.speed(this.settings.dragEndSpeed||this.settings.smartSpeed);this.current(b);this.invalidate("position");this.update();this.settings.pullDrag||this.drag.updatedX!==this.coordinates(b)||this.transitionEnd();this.drag.distance=
0;a(k).off(".owl.dragEvents")}};c.prototype.removeClick=function(b){this.drag.targetEl=b;a(b).on("click.preventClick",this.e._preventClick);e.setTimeout(function(){a(b).off("click.preventClick")},300)};c.prototype.preventClick=function(b){b.preventDefault?b.preventDefault():b.returnValue=!1;b.stopPropagation&&b.stopPropagation();a(b.target).off("click.preventClick")};c.prototype.getTransformProperty=function(){var b=e.getComputedStyle(this.$stage.get(0),null).getPropertyValue(this.vendorName+"transform");
b=b.replace(/matrix(3d)?\(|\)/g,"").split(",");return 16===b.length!==!0?b[4]:b[12]};c.prototype.closest=function(b){var d=-1,c=this.width(),f=this.coordinates();this.settings.freeDrag||a.each(f,a.proxy(function(a,g){b>g-30&&b<g+30?d=a:this.op(b,"<",g)&&this.op(b,">",f[a+1]||g-c)&&(d="left"===this.state.direction?a+1:a);return-1===d},this));this.settings.loop||(this.op(b,">",f[this.minimum()])?d=b=this.minimum():this.op(b,"<",f[this.maximum()])&&(d=b=this.maximum()));return d};c.prototype.animate=
function(b){this.trigger("translate");this.state.inMotion=0<this.speed();this.support3d?this.$stage.css({transform:"translate3d("+b+"px,0px, 0px)",transition:this.speed()/1E3+"s"}):this.state.isTouch?this.$stage.css({left:b+"px"}):this.$stage.animate({left:b},this.speed()/1E3,this.settings.fallbackEasing,a.proxy(function(){this.state.inMotion&&this.transitionEnd()},this))};c.prototype.current=function(b){if(b===h)return this._current;if(0===this._items.length)return h;b=this.normalize(b);if(this._current!==
b){var a=this.trigger("change",{property:{name:"position",value:b}});a.data!==h&&(b=this.normalize(a.data));this._current=b;this.invalidate("position");this.trigger("changed",{property:{name:"position",value:this._current}})}return this._current};c.prototype.invalidate=function(b){this._invalidated[b]=!0};c.prototype.reset=function(b){b=this.normalize(b);b!==h&&(this._speed=0,this._current=b,this.suppress(["translate","translated"]),this.animate(this.coordinates(b)),this.release(["translate","translated"]))};
c.prototype.normalize=function(b,d){var c=d?this._items.length:this._items.length+this._clones.length;return!a.isNumeric(b)||1>c?h:b=this._clones.length?(b%c+c)%c:Math.max(this.minimum(d),Math.min(this.maximum(d),b))};c.prototype.relative=function(b){b=this.normalize(b);b-=this._clones.length/2;return this.normalize(b,!0)};c.prototype.maximum=function(b){var a=0;var d=this.settings;if(b)return this._items.length-1;if(!d.loop&&d.center)var c=this._items.length-1;else if(d.loop||d.center)if(d.loop||
d.center)c=this._items.length+d.items;else if(d.autoWidth||d.merge)for(revert=d.rtl?1:-1,b=this.$stage.width()-this.$element.width();(d=this.coordinates(a))&&!(d*revert>=b);)c=++a;else throw"Can not detect maximum absolute position.";else c=this._items.length-d.items;return c};c.prototype.minimum=function(b){return b?0:this._clones.length/2};c.prototype.items=function(b){if(b===h)return this._items.slice();b=this.normalize(b,!0);return this._items[b]};c.prototype.mergers=function(b){if(b===h)return this._mergers.slice();
b=this.normalize(b,!0);return this._mergers[b]};c.prototype.clones=function(b){var d=this._clones.length/2,c=d+this._items.length;return b===h?a.map(this._clones,function(b,a){return 0===a%2?c+a/2:d-(a+1)/2}):a.map(this._clones,function(a,f){return a===b?0===f%2?c+f/2:d-(f+1)/2:null})};c.prototype.speed=function(b){b!==h&&(this._speed=b);return this._speed};c.prototype.coordinates=function(b){var d=null;if(b===h)return a.map(this._coordinates,a.proxy(function(b,a){return this.coordinates(a)},this));
this.settings.center?(d=this._coordinates[b],d+=(this.width()-d+(this._coordinates[b-1]||0))/2*(this.settings.rtl?-1:1)):d=this._coordinates[b-1]||0;return d};c.prototype.duration=function(b,a,d){return Math.min(Math.max(Math.abs(a-b),1),6)*Math.abs(d||this.settings.smartSpeed)};c.prototype.to=function(b,d){if(this.settings.loop){var c=b-this.relative(this.current()),f=this.current();b=this.current();var g=this.current()+c,q=0>b-g?!0:!1,l=this._clones.length+this._items.length;g<this.settings.items&&
!1===q?(f=b+this._items.length,this.reset(f)):g>=l-this.settings.items&&!0===q&&(f=b-this._items.length,this.reset(f));e.clearTimeout(this.e._goToLoop);this.e._goToLoop=e.setTimeout(a.proxy(function(){this.speed(this.duration(this.current(),f+c,d));this.current(f+c);this.update()},this),30)}else this.speed(this.duration(this.current(),b,d)),this.current(b),this.update()};c.prototype.next=function(b){b=b||!1;this.to(this.relative(this.current())+1,b)};c.prototype.prev=function(b){b=b||!1;this.to(this.relative(this.current())-
1,b)};c.prototype.transitionEnd=function(b){if(b!==h&&(b.stopPropagation(),(b.target||b.srcElement||b.originalTarget)!==this.$stage.get(0)))return!1;this.state.inMotion=!1;this.trigger("translated")};c.prototype.viewport=function(){if(this.options.responsiveBaseElement!==e)var b=a(this.options.responsiveBaseElement).width();else if(e.innerWidth)b=e.innerWidth;else if(k.documentElement&&k.documentElement.clientWidth)b=k.documentElement.clientWidth;else throw"Can not detect viewport width.";return b};
c.prototype.replace=function(b){this.$stage.empty();this._items=[];b&&(b=b instanceof jQuery?b:a(b));this.settings.nestedItemSelector&&(b=b.find("."+this.settings.nestedItemSelector));b.filter(function(){return 1===this.nodeType}).each(a.proxy(function(b,a){a=this.prepare(a);this.$stage.append(a);this._items.push(a);this._mergers.push(1*a.find("[data-merge]").andSelf("[data-merge]").attr("data-merge")||1)},this));this.reset(a.isNumeric(this.settings.startPosition)?this.settings.startPosition:0);this.invalidate("items")};
c.prototype.add=function(b,a){a=a===h?this._items.length:this.normalize(a,!0);this.trigger("add",{content:b,position:a});0===this._items.length||a===this._items.length?(this.$stage.append(b),this._items.push(b),this._mergers.push(1*b.find("[data-merge]").andSelf("[data-merge]").attr("data-merge")||1)):(this._items[a].before(b),this._items.splice(a,0,b),this._mergers.splice(a,0,1*b.find("[data-merge]").andSelf("[data-merge]").attr("data-merge")||1));this.invalidate("items");this.trigger("added",{content:b,
position:a})};c.prototype.remove=function(b){b=this.normalize(b,!0);b!==h&&(this.trigger("remove",{content:this._items[b],position:b}),this._items[b].remove(),this._items.splice(b,1),this._mergers.splice(b,1),this.invalidate("items"),this.trigger("removed",{content:null,position:b}))};c.prototype.addTriggerableEvents=function(){var b=a.proxy(function(b,d){return a.proxy(function(a){a.relatedTarget!==this&&(this.suppress([d]),b.apply(this,[].slice.call(arguments,1)),this.release([d]))},this)},this);
a.each({next:this.next,prev:this.prev,to:this.to,destroy:this.destroy,refresh:this.refresh,replace:this.replace,add:this.add,remove:this.remove},a.proxy(function(a,d){this.$element.on(a+".owl.carousel",b(d,a+".owl.carousel"))},this))};c.prototype.watchVisibility=function(){function b(b){return 0<b.offsetWidth&&0<b.offsetHeight}function d(){b(this.$element.get(0))&&(this.$element.removeClass("owl-hidden"),this.refresh(),e.clearInterval(this.e._checkVisibile))}b(this.$element.get(0))||(this.$element.addClass("owl-hidden"),
e.clearInterval(this.e._checkVisibile),this.e._checkVisibile=e.setInterval(a.proxy(d,this),500))};c.prototype.preloadAutoWidthImages=function(b){var d,c;var f=0;var g=this;b.each(function(e,l){d=a(l);c=new Image;c.onload=function(){f++;d.attr("src",c.src);d.css("opacity",1);f>=b.length&&(g.state.imagesLoaded=!0,g.initialize())};c.src=d.attr("src")||d.attr("data-src")||d.attr("data-src-retina")})};c.prototype.destroy=function(){this.$element.hasClass(this.settings.themeClass)&&this.$element.removeClass(this.settings.themeClass);
!1!==this.settings.responsive&&a(e).off("resize.owl.carousel");this.transitionEndVendor&&this.off(this.$stage.get(0),this.transitionEndVendor,this.e._transitionEnd);for(var b in this._plugins)this._plugins[b].destroy();if(this.settings.mouseDrag||this.settings.touchDrag)this.$stage.off("mousedown touchstart touchcancel"),a(k).off(".owl.dragEvents"),this.$stage.get(0).onselectstart=function(){},this.$stage.off("dragstart",function(){return!1});this.$element.off(".owl");this.$stage.children(".cloned").remove();
this.e=null;this.$element.removeData("owlCarousel");this.$stage.children().contents().unwrap();this.$stage.children().unwrap();this.$stage.unwrap()};c.prototype.op=function(b,a,d){var c=this.settings.rtl;switch(a){case "<":return c?b>d:b<d;case ">":return c?b<d:b>d;case ">=":return c?b<=d:b>=d;case "<=":return c?b>=d:b<=d}};c.prototype.on=function(b,a,d,c){b.addEventListener?b.addEventListener(a,d,c):b.attachEvent&&b.attachEvent("on"+a,d)};c.prototype.off=function(b,a,d,c){b.removeEventListener?b.removeEventListener(a,
d,c):b.detachEvent&&b.detachEvent("on"+a,d)};c.prototype.trigger=function(b,d,c){var f={item:{count:this._items.length,index:this.current()}},g=a.camelCase(a.grep(["on",b,c],function(b){return b}).join("-").toLowerCase()),e=a.Event([b,"owl",c||"carousel"].join(".").toLowerCase(),a.extend({relatedTarget:this},f,d));this._supress[b]||(a.each(this._plugins,function(b,a){if(a.onTrigger)a.onTrigger(e)}),this.$element.trigger(e),this.settings&&"function"===typeof this.settings[g]&&this.settings[g].apply(this,
e));return e};c.prototype.suppress=function(b){a.each(b,a.proxy(function(b,a){this._supress[a]=!0},this))};c.prototype.release=function(b){a.each(b,a.proxy(function(b,a){delete this._supress[a]},this))};c.prototype.browserSupport=function(){if(this.support3d=d(["perspective","webkitPerspective","MozPerspective","OPerspective","MsPerspective"])[0])this.transformVendor=d(["transform","WebkitTransform","MozTransform","OTransform","msTransform"])[0],this.transitionEndVendor=["transitionend","webkitTransitionEnd",
"transitionend","oTransitionEnd"][d(["transition","WebkitTransition","MozTransition","OTransition"])[1]],this.vendorName=this.transformVendor.replace(/Transform/i,""),this.vendorName=""!==this.vendorName?"-"+this.vendorName.toLowerCase()+"-":"";this.state.orientation=e.orientation};a.fn.owlCarousel=function(b){return this.each(function(){a(this).data("owlCarousel")||a(this).data("owlCarousel",new c(this,b))})};a.fn.owlCarousel.Constructor=c})(window.Zepto||window.jQuery,window,document);
(function(a,e,k,h){var c=function(f){this._core=f;this._loaded=[];this._handlers={"initialized.owl.carousel change.owl.carousel":a.proxy(function(d){if(d.namespace&&this._core.settings&&this._core.settings.lazyLoad&&(d.property&&"position"==d.property.name||"initialized"==d.type)){var c=this._core.settings,f=c.center&&Math.ceil(c.items/2)||c.items;c=c.center&&-1*f||0;d=(d.property&&d.property.value||this._core.current())+c;for(var e=this._core.clones().length,b=a.proxy(function(b,a){this.load(a)},
this);c++<f;)this.load(e/2+this._core.relative(d)),e&&a.each(this._core.clones(this._core.relative(d++)),b)}},this)};this._core.options=a.extend({},c.Defaults,this._core.options);this._core.$element.on(this._handlers)};c.Defaults={lazyLoad:!1};c.prototype.load=function(c){var d=(c=this._core.$stage.children().eq(c))&&c.find(".owl-lazy");!d||-1<a.inArray(c.get(0),this._loaded)||(d.each(a.proxy(function(d,c){var f=a(c),b=1<e.devicePixelRatio&&f.attr("data-src-retina")||f.attr("data-src");this._core.trigger("load",
{element:f,url:b},"lazy");f.is("img")?f.one("load.owl.lazy",a.proxy(function(){f.css("opacity",1);this._core.trigger("loaded",{element:f,url:b},"lazy")},this)).attr("src",b):(d=new Image,d.onload=a.proxy(function(){f.css({"background-image":"url("+b+")",opacity:"1"});this._core.trigger("loaded",{element:f,url:b},"lazy")},this),d.src=b)},this)),this._loaded.push(c.get(0)))};c.prototype.destroy=function(){var a,d;for(a in this.handlers)this._core.$element.off(a,this.handlers[a]);for(d in Object.getOwnPropertyNames(this))"function"!=
typeof this[d]&&(this[d]=null)};a.fn.owlCarousel.Constructor.Plugins.Lazy=c})(window.Zepto||window.jQuery,window,document);
(function(a,e,k,h){var c=function(f){this._core=f;this._handlers={"initialized.owl.carousel":a.proxy(function(){this._core.settings.autoHeight&&this.update()},this),"changed.owl.carousel":a.proxy(function(a){this._core.settings.autoHeight&&"position"==a.property.name&&this.update()},this),"loaded.owl.lazy":a.proxy(function(a){this._core.settings.autoHeight&&a.element.closest("."+this._core.settings.itemClass)===this._core.$stage.children().eq(this._core.current())&&this.update()},this)};this._core.options=
a.extend({},c.Defaults,this._core.options);this._core.$element.on(this._handlers)};c.Defaults={autoHeight:!1,autoHeightClass:"owl-height"};c.prototype.update=function(){this._core.$stage.parent().height(this._core.$stage.children().eq(this._core.current()).height()).addClass(this._core.settings.autoHeightClass)};c.prototype.destroy=function(){var a,d;for(a in this._handlers)this._core.$element.off(a,this._handlers[a]);for(d in Object.getOwnPropertyNames(this))"function"!=typeof this[d]&&(this[d]=
null)};a.fn.owlCarousel.Constructor.Plugins.AutoHeight=c})(window.Zepto||window.jQuery,window,document);
(function(a,e,k,h){var c=function(f){this._core=f;this._videos={};this._playing=null;this._fullscreen=!1;this._handlers={"resize.owl.carousel":a.proxy(function(a){this._core.settings.video&&!this.isInFullScreen()&&a.preventDefault()},this),"refresh.owl.carousel changed.owl.carousel":a.proxy(function(a){this._playing&&this.stop()},this),"prepared.owl.carousel":a.proxy(function(d){var c=a(d.content).find(".owl-video");c.length&&(c.css("display","none"),this.fetch(c,a(d.content)))},this)};this._core.options=
a.extend({},c.Defaults,this._core.options);this._core.$element.on(this._handlers);this._core.$element.on("click.owl.video",".owl-video-play-icon",a.proxy(function(a){this.play(a)},this))};c.Defaults={video:!1,videoHeight:!1,videoWidth:!1};c.prototype.fetch=function(a,d){a.attr("data-vimeo-id");a.attr("data-vimeo-id")||a.attr("data-youtube-id");var c=a.attr("data-width")||this._core.settings.videoWidth,f=a.attr("data-height")||this._core.settings.videoHeight,e=a.attr("href");if(e){var b=e.match(/(http:|https:|)\/\/(player.|www.)?(vimeo\.com|youtu(be\.com|\.be|be\.googleapis\.com))\/(video\/|embed\/|watch\?v=|v\/)?([A-Za-z0-9._%-]*)(&\S+)?/);
if(-1<b[3].indexOf("youtu"))var h="youtube";else if(-1<b[3].indexOf("vimeo"))h="vimeo";else throw Error("Video URL not supported.");b=b[6]}else throw Error("Missing video URL.");this._videos[e]={type:h,id:b,width:c,height:f};d.attr("data-video",e);this.thumbnail(a,this._videos[e])};c.prototype.thumbnail=function(c,d){var f,e=d.width&&d.height?'style="width:'+d.width+"px;height:"+d.height+'px;"':"",h=c.find("img"),b="src",k="",r=this._core.settings,n=function(a){f=r.lazyLoad?'<div class="owl-video-tn '+
k+'" '+b+'="'+a+'"></div>':'<div class="owl-video-tn" style="opacity:1;background-image:url('+a+')"></div>';c.after(f);c.after('<div class="owl-video-play-icon"></div>')};c.wrap('<div class="owl-video-wrapper"'+e+"></div>");this._core.settings.lazyLoad&&(b="data-src",k="owl-lazy");if(h.length)return n(h.attr(b)),h.remove(),!1;if("youtube"===d.type){var p="http://img.youtube.com/vi/"+d.id+"/hqdefault.jpg";n(p)}else"vimeo"===d.type&&a.ajax({type:"GET",url:"http://vimeo.com/api/v2/video/"+d.id+".json",
jsonp:"callback",dataType:"jsonp",success:function(b){p=b[0].thumbnail_large;n(p)}})};c.prototype.stop=function(){this._core.trigger("stop",null,"video");this._playing.find(".owl-video-frame").remove();this._playing.removeClass("owl-video-playing");this._playing=null};c.prototype.play=function(c){this._core.trigger("play",null,"video");this._playing&&this.stop();c=a(c.target||c.srcElement);var d=c.closest("."+this._core.settings.itemClass),f=this._videos[d.attr("data-video")],e=f.width||"100%",h=
f.height||this._core.$stage.height(),b;"youtube"===f.type?b='<iframe width="'+e+'" height="'+h+'" src="http://www.youtube.com/embed/'+f.id+"?autoplay=1&v="+f.id+'" frameborder="0" allowfullscreen></iframe>':"vimeo"===f.type&&(b='<iframe src="http://player.vimeo.com/video/'+f.id+'?autoplay=1" width="'+e+'" height="'+h+'" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>');d.addClass("owl-video-playing");this._playing=d;b=a('<div style="height:'+h+"px; width:"+e+'px" class="owl-video-frame">'+
b+"</div>");c.after(b)};c.prototype.isInFullScreen=function(){var c=k.fullscreenElement||k.mozFullScreenElement||k.webkitFullscreenElement;c&&a(c).parent().hasClass("owl-video-frame")&&(this._core.speed(0),this._fullscreen=!0);return c&&this._fullscreen&&this._playing?!1:this._fullscreen?this._fullscreen=!1:this._playing&&this._core.state.orientation!==e.orientation?(this._core.state.orientation=e.orientation,!1):!0};c.prototype.destroy=function(){var a,d;this._core.$element.off("click.owl.video");
for(a in this._handlers)this._core.$element.off(a,this._handlers[a]);for(d in Object.getOwnPropertyNames(this))"function"!=typeof this[d]&&(this[d]=null)};a.fn.owlCarousel.Constructor.Plugins.Video=c})(window.Zepto||window.jQuery,window,document);
(function(a,e,k,h){var c=function(f){this.core=f;this.core.options=a.extend({},c.Defaults,this.core.options);this.swapping=!0;this.next=this.previous=h;this.handlers={"change.owl.carousel":a.proxy(function(a){"position"==a.property.name&&(this.previous=this.core.current(),this.next=a.property.value)},this),"drag.owl.carousel dragged.owl.carousel translated.owl.carousel":a.proxy(function(a){this.swapping="translated"==a.type},this),"translate.owl.carousel":a.proxy(function(a){this.swapping&&(this.core.options.animateOut||
this.core.options.animateIn)&&this.swap()},this)};this.core.$element.on(this.handlers)};c.Defaults={animateOut:!1,animateIn:!1};c.prototype.swap=function(){if(1===this.core.settings.items&&this.core.support3d){this.core.speed(0);var c=a.proxy(this.clear,this),d=this.core.$stage.children().eq(this.previous),g=this.core.$stage.children().eq(this.next),e=this.core.settings.animateIn,h=this.core.settings.animateOut;if(this.core.current()!==this.previous){if(h){var b=this.core.coordinates(this.previous)-
this.core.coordinates(this.next);d.css({left:b+"px"}).addClass("animated owl-animated-out").addClass(h).one("webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend",c)}if(e)g.addClass("animated owl-animated-in").addClass(e).one("webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend",c)}}};c.prototype.clear=function(c){a(c.target).css({left:""}).removeClass("animated owl-animated-out owl-animated-in").removeClass(this.core.settings.animateIn).removeClass(this.core.settings.animateOut);
this.core.transitionEnd()};c.prototype.destroy=function(){var a,d;for(a in this.handlers)this.core.$element.off(a,this.handlers[a]);for(d in Object.getOwnPropertyNames(this))"function"!=typeof this[d]&&(this[d]=null)};a.fn.owlCarousel.Constructor.Plugins.Animate=c})(window.Zepto||window.jQuery,window,document);
(function(a,e,k,h){var c=function(f){this.core=f;this.core.options=a.extend({},c.Defaults,this.core.options);this.handlers={"translated.owl.carousel refreshed.owl.carousel":a.proxy(function(){this.autoplay()},this),"play.owl.autoplay":a.proxy(function(a,c,f){this.play(c,f)},this),"stop.owl.autoplay":a.proxy(function(){this.stop()},this),"mouseover.owl.autoplay":a.proxy(function(){this.core.settings.autoplayHoverPause&&this.pause()},this),"mouseleave.owl.autoplay":a.proxy(function(){this.core.settings.autoplayHoverPause&&
this.autoplay()},this)};this.core.$element.on(this.handlers)};c.Defaults={autoplay:!1,autoplayTimeout:5E3,autoplayHoverPause:!1,autoplaySpeed:!1};c.prototype.autoplay=function(){this.core.settings.autoplay&&!this.core.state.videoPlay?(e.clearInterval(this.interval),this.interval=e.setInterval(a.proxy(function(){this.play()},this),this.core.settings.autoplayTimeout)):e.clearInterval(this.interval)};c.prototype.play=function(a,d){!0!==k.hidden&&(this.core.state.isTouch||this.core.state.isScrolling||
this.core.state.isSwiping||this.core.state.inMotion||(!1===this.core.settings.autoplay?e.clearInterval(this.interval):this.core.next(this.core.settings.autoplaySpeed)))};c.prototype.stop=function(){e.clearInterval(this.interval)};c.prototype.pause=function(){e.clearInterval(this.interval)};c.prototype.destroy=function(){var a,d;e.clearInterval(this.interval);for(a in this.handlers)this.core.$element.off(a,this.handlers[a]);for(d in Object.getOwnPropertyNames(this))"function"!=typeof this[d]&&(this[d]=
null)};a.fn.owlCarousel.Constructor.Plugins.autoplay=c})(window.Zepto||window.jQuery,window,document);
(function(a,e,k,h){var c=function(f){this._core=f;this._initialized=!1;this._pages=[];this._controls={};this._templates=[];this.$element=this._core.$element;this._overrides={next:this._core.next,prev:this._core.prev,to:this._core.to};this._handlers={"prepared.owl.carousel":a.proxy(function(d){this._core.settings.dotsData&&this._templates.push(a(d.content).find("[data-dot]").andSelf("[data-dot]").attr("data-dot"))},this),"add.owl.carousel":a.proxy(function(d){this._core.settings.dotsData&&this._templates.splice(d.position,
0,a(d.content).find("[data-dot]").andSelf("[data-dot]").attr("data-dot"))},this),"remove.owl.carousel prepared.owl.carousel":a.proxy(function(a){this._core.settings.dotsData&&this._templates.splice(a.position,1)},this),"change.owl.carousel":a.proxy(function(a){if("position"==a.property.name&&!this._core.state.revert&&!this._core.settings.loop&&this._core.settings.navRewind){var d=this._core.current(),c=this._core.maximum(),f=this._core.minimum();a.data=a.property.value>c?d>=c?f:c:a.property.value<
f?c:a.property.value}},this),"changed.owl.carousel":a.proxy(function(a){"position"==a.property.name&&this.draw()},this),"refreshed.owl.carousel":a.proxy(function(){this._initialized||(this.initialize(),this._initialized=!0);this._core.trigger("refresh",null,"navigation");this.update();this.draw();this._core.trigger("refreshed",null,"navigation")},this)};this._core.options=a.extend({},c.Defaults,this._core.options);this.$element.on(this._handlers)};c.Defaults={nav:!1,navRewind:!0,navText:["prev","next"],
navSpeed:!1,navElement:"div",navContainer:!1,navContainerClass:"owl-nav",navClass:["owl-prev","owl-next"],slideBy:1,dotClass:"owl-dot",dotsClass:"owl-dots",dots:!0,dotsEach:!1,dotData:!1,dotsSpeed:!1,dotsContainer:!1,controlsClass:"owl-controls"};c.prototype.initialize=function(){var c,d=this._core.settings;d.dotsData||(this._templates=[a("<div>").addClass(d.dotClass).append(a("<span>")).prop("outerHTML")]);d.navContainer&&d.dotsContainer||(this._controls.$container=a("<div>").addClass(d.controlsClass).appendTo(this.$element));
this._controls.$indicators=d.dotsContainer?a(d.dotsContainer):a("<div>").hide().addClass(d.dotsClass).appendTo(this._controls.$container);this._controls.$indicators.on("click","div",a.proxy(function(c){var f=a(c.target).parent().is(this._controls.$indicators)?a(c.target).index():a(c.target).parent().index();c.preventDefault();this.to(f,d.dotsSpeed)},this));var g=d.navContainer?a(d.navContainer):a("<div>").addClass(d.navContainerClass).prependTo(this._controls.$container);this._controls.$next=a("<"+
d.navElement+">");this._controls.$previous=this._controls.$next.clone();this._controls.$previous.addClass(d.navClass[0]).html(d.navText[0]).hide().prependTo(g).on("click",a.proxy(function(a){this.prev(d.navSpeed)},this));this._controls.$next.addClass(d.navClass[1]).html(d.navText[1]).hide().appendTo(g).on("click",a.proxy(function(a){this.next(d.navSpeed)},this));for(c in this._overrides)this._core[c]=a.proxy(this[c],this)};c.prototype.destroy=function(){var a,c,g,e;for(a in this._handlers)this.$element.off(a,
this._handlers[a]);for(c in this._controls)this._controls[c].remove();for(e in this.overides)this._core[e]=this._overrides[e];for(g in Object.getOwnPropertyNames(this))"function"!=typeof this[g]&&(this[g]=null)};c.prototype.update=function(){var a,c;var g=this._core.settings;var e=this._core.clones().length/2,h=e+this._core.items().length,b=g.center||g.autoWidth||g.dotData?1:g.dotsEach||g.items;"page"!==g.slideBy&&(g.slideBy=Math.min(g.slideBy,g.items));if(g.dots||"page"==g.slideBy)for(this._pages=
[],g=e,c=a=0;g<h;g++){if(a>=b||0===a)this._pages.push({start:g-e,end:g-e+b-1}),a=0,++c;a+=this._core.mergers(this._core.relative(g))}};c.prototype.draw=function(){var c="",d=this._core.settings;this._core.$stage.children();var e=this._core.relative(this._core.current());!d.nav||d.loop||d.navRewind||(this._controls.$previous.toggleClass("disabled",0>=e),this._controls.$next.toggleClass("disabled",e>=this._core.maximum()));this._controls.$previous.toggle(d.nav);this._controls.$next.toggle(d.nav);if(d.dots){e=
this._pages.length-this._controls.$indicators.children().length;if(d.dotData&&0!==e){for(e=0;e<this._controls.$indicators.children().length;e++)c+=this._templates[this._core.relative(e)];this._controls.$indicators.html(c)}else 0<e?(c=Array(e+1).join(this._templates[0]),this._controls.$indicators.append(c)):0>e&&this._controls.$indicators.children().slice(e).remove();this._controls.$indicators.find(".active").removeClass("active");this._controls.$indicators.children().eq(a.inArray(this.current(),this._pages)).addClass("active")}this._controls.$indicators.toggle(d.dots)};
c.prototype.onTrigger=function(c){var d=this._core.settings;c.page={index:a.inArray(this.current(),this._pages),count:this._pages.length,size:d&&(d.center||d.autoWidth||d.dotData?1:d.dotsEach||d.items)}};c.prototype.current=function(){var c=this._core.relative(this._core.current());return a.grep(this._pages,function(a){return a.start<=c&&a.end>=c}).pop()};c.prototype.getPosition=function(c){var d=this._core.settings;if("page"==d.slideBy){var f=a.inArray(this.current(),this._pages);d=this._pages.length;
c?++f:--f;f=this._pages[(f%d+d)%d].start}else f=this._core.relative(this._core.current()),this._core.items(),c?f+=d.slideBy:f-=d.slideBy;return f};c.prototype.next=function(c){a.proxy(this._overrides.to,this._core)(this.getPosition(!0),c)};c.prototype.prev=function(c){a.proxy(this._overrides.to,this._core)(this.getPosition(!1),c)};c.prototype.to=function(c,d,e){e?a.proxy(this._overrides.to,this._core)(c,d):(e=this._pages.length,a.proxy(this._overrides.to,this._core)(this._pages[(c%e+e)%e].start,d))};
a.fn.owlCarousel.Constructor.Plugins.Navigation=c})(window.Zepto||window.jQuery,window,document);
(function(a,e,k,h){var c=function(f){this._core=f;this._hashes={};this.$element=this._core.$element;this._handlers={"initialized.owl.carousel":a.proxy(function(){"URLHash"==this._core.settings.startPosition&&a(e).trigger("hashchange.owl.navigation")},this),"prepared.owl.carousel":a.proxy(function(c){var d=a(c.content).find("[data-hash]").andSelf("[data-hash]").attr("data-hash");this._hashes[d]=c.content},this)};this._core.options=a.extend({},c.Defaults,this._core.options);this.$element.on(this._handlers);
a(e).on("hashchange.owl.navigation",a.proxy(function(){var a=e.location.hash.substring(1),c=this._core.$stage.children();c=this._hashes[a]&&c.index(this._hashes[a])||0;if(!a)return!1;this._core.to(c,!1,!0)},this))};c.Defaults={URLhashListener:!1};c.prototype.destroy=function(){var c,d;a(e).off("hashchange.owl.navigation");for(c in this._handlers)this._core.$element.off(c,this._handlers[c]);for(d in Object.getOwnPropertyNames(this))"function"!=typeof this[d]&&(this[d]=null)};a.fn.owlCarousel.Constructor.Plugins.Hash=
c})(window.Zepto||window.jQuery,window,document);
